### ISSUE TITLE
Pylint results

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-4-documentation-and-style-JessicaLiu21#1]
There's no pylint output in your repository. When I run pylint on your code, it has a score lower than 8.

(-2 points)

Here's the pylint output
```
» pylint documentation.py
************* Module documentation
documentation.py:2:29: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:8:33: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:10:48: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:12:62: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:24:18: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:26:69: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:29:18: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:31:74: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:35:65: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:36:32: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:44:17: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:45:84: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:48:17: C0303: Trailing whitespace (trailing-whitespace)
documentation.py:52:0: C0305: Trailing newlines (trailing-newlines)

-----------------------------------
Your code has been rated at 4.81/10
```

**Comment by JessicaLiu21** [comment]
> There's no pylint output in your repository. When I run pylint on your code, it has a score lower than 8.
> 
> (-2 points)
> 
> Here's the pylint output
> 
> ```
> » pylint documentation.py
> ************* Module documentation
> documentation.py:2:29: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:8:33: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:10:48: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:12:62: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:24:18: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:26:69: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:29:18: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:31:74: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:35:65: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:36:32: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:44:17: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:45:84: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:48:17: C0303: Trailing whitespace (trailing-whitespace)
> documentation.py:52:0: C0305: Trailing newlines (trailing-newlines)
> 
> -----------------------------------
> Your code has been rated at 4.81/10
> ```

Sorry. I met some problem when I used the Pylint. I then caught a cold and missed the opportunity to  fix on class. I have added it just now, Could you check that? Thanks

**Comment by dcjones** [comment]
Looks good: 7/7 points
