### ISSUE TITLE
Function documentation missing argument descriptions

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-4-documentation-and-style-JessicaLiu21#2]
Function documentation should include a description the the arguments and return
types. [-1 point]

**Comment by JessicaLiu21** [comment]
I have fixed that. Could you check it again? Thanks!

**Comment by JessicaLiu21** [comment]
> Function documentation should include a description the the arguments and return
> types. [-1 point]

I have fixed that. Could you check it again? Thanks

**Comment by dcjones** [comment]
Looks good, both issues are resolved. 7/7 points.
